name: development blog
source: "."
dest: "build"
ignore: [.git/*, build/*]
post_path: /posts/:slug

rss: rss.xml
name: Shimi Paper Fish devlog - Don't Expect Anything Sensible
description: The on-going development diary of a fishing game
link: https://shimipaperfish.dontexpectanythingsensible.uk